spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: markhan
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true // 이거보단 logger로 찍자.
        format_sql: true
    database: postgresql

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
