name: Build and Deploy to EC2

on:
  push:
    branches:
      - master
      
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run : chmod +x gradlew

      - name: Build with Gradle without Test
        run: ./gradlew clean build -x test

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cicdsample
          path: build/libs/*.jar
        

  deploy:
    needs: build
    runs-on: ubuntu-latest
  
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: cicdsample
          
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          
      - name: Scp transfer
        run: scp cicdsample ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/cicd
          
      - name: SSH into EC2 and run JAR file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/cicd
            nohup java -jar verifit-0.0.1-SNAPSHOT.jar &
