name: Build and Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run : chmod +x gradlew

      - name: Build with Gradle without Test
        run: ./gradlew clean build -x test

      - name: Make Directory for delivery
        run: mkdir deploy

      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy/

  deploy:
    needs: build
    runs-on: ubuntu-latest
  
    steps:
      - name: Make zip file
        run: zip -r -qq -j ./sprintboot-build.zip ./deploy

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./springboot-build.zip"
          target: "~/cicd"
          overwrite: true
          
      - name: SSH into EC2 and run JAR file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/backend/build/libs/
            nohup java -jar verifit-0.0.1-SNAPSHOT.jar &
